[versions]
checkerframework = "3.37.0"
fastutil = "8.5.13-SNAPSHOT"
netty = "4.1.101.Final"

[libraries]
checker-qual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerframework" }
checker = { group = "org.checkerframework", name = "checker", version.ref = "checkerframework" }

fastutil-long-common = { group = "org.cloudburstmc.fastutil.commons", name = "long-common", version.ref = "fastutil" }
fastutil-long-object-maps = { group = "org.cloudburstmc.fastutil.maps", name = "long-object-maps", version.ref = "fastutil" }
fastutil-int-object-maps = { group = "org.cloudburstmc.fastutil.maps", name = "int-object-maps", version.ref = "fastutil" }
fastutil-object-int-maps = { group = "org.cloudburstmc.fastutil.maps", name = "object-int-maps", version.ref = "fastutil" }

netty-buffer = { group = "io.netty", name = "netty-buffer", version.ref = "netty" }
netty-transport-raknet = { group = "org.cloudburstmc.netty", name = "netty-transport-raknet", version = "1.0.0.CR1-SNAPSHOT" }

jose4j = { group = "org.bitbucket.b_c", name = "jose4j", version = "0.9.3" }
natives = { group = "com.nukkitx", name = "natives", version = "1.0.3" }
math = { group = "org.cloudburstmc.math", name = "immutable", version = "2.0-SNAPSHOT" }
nbt = { group = "org.cloudburstmc", name = "nbt", version = "3.0.2.Final" }
lmbda = { group = "org.lanternpowered", name = "lmbda", version = "2.0.0" }

snappy = { group = "io.airlift", name = "aircompressor", version = "0.25" }

[plugins]
checkerframework = { id = "org.checkerframework", version = "0.6.29" }
lombok = { id = "io.freefair.lombok", version = "6.6.3" }
