[versions]
checkerframework = "3.26.0"
fastutil = "8.5.3"
netty = "4.1.84.Final"

[libraries]
checker-qual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerframework" }
checker = { group = "org.checkerframework", name = "checker", version.ref = "checkerframework" }

fastutil-long-common = { group = "com.nukkitx.fastutil", name = "fastutil-long-common", version.ref = "fastutil" }
fastutil-long-object-maps = { group = "com.nukkitx.fastutil", name = "fastutil-long-object-maps", version.ref = "fastutil" }
fastutil-int-object-maps = { group = "com.nukkitx.fastutil", name = "fastutil-int-object-maps", version.ref = "fastutil" }
fastutil-object-int-maps = { group = "com.nukkitx.fastutil", name = "fastutil-object-int-maps", version.ref = "fastutil" }

netty-buffer = { group = "io.netty", name = "netty-buffer", version.ref = "netty" }
netty-transport-raknet = { group = "org.cloudburstmc.netty", name = "netty-transport-raknet", version = "0.0.1.Final-SNAPSHOT" }

jose-jwt = { group = "com.nimbusds", name = "nimbus-jose-jwt", version = "9.10.1" }
natives = { group = "com.nukkitx", name = "natives", version = "1.0.3" }
math = { group = "org.cloudburstmc.math", name = "immutable", version = "2.0-SNAPSHOT" }
nbt = { group = "org.cloudburstmc", name = "nbt", version = "3.0.0.Final" }
lmbda = { group = "org.lanternpowered", name = "lmbda", version = "2.0.0" }

snappy = { group = "io.airlift", name = "aircompressor", version = "0.21" }

[plugins]
checkerframework = { id = "org.checkerframework", version = "0.6.18" }
lombok = { id = "io.freefair.lombok", version = "6.5.1" }