on:
  workflow_call:
    inputs:
      deploy-url:
        description: 'The maven repository to deploy to'
        required: true
        type: string
    secrets:
      DEPLOY_USERNAME:
        required: true
      DEPLOY_PASSWORD:
        required: true
      PGP_SECRET:
        required: true
      PGP_PASSPHRASE:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: "publish"
        env:
          MAVEN_DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          MAVEN_DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          MAVEN_DEPLOY_URL: ${{ inputs.deploy-url }}
