name: Deploy Snapshot
on:
  push:
    branches:
      - '3.0'

jobs:
  deploy:
    uses: CloudburstMC/Protocol/.github/workflows/deploy.yml@3.0
    with:
      deploy-url: "https://repo.opencollab.dev/maven-deploy-snapshot/"
    secrets:
      DEPLOY_USERNAME: ${{ vars.OPENCOLLAB_USERNAME }}
      DEPLOY_PASSWORD: ${{ secrets.OPENCOLLAB_PASSWORD }}
      PGP_SECRET: ${{ secrets.MAVEN_CENTRAL_SECRET }}
      PGP_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_PASSPHRASE }}
